server:
  port: 8080
spring:
  application:
    name: "TodoList"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  datasource:
    url: "jdbc:h2:mem:test"
    username: "sa"
    password: "pass"
    driverClassName: "org.h2.Driver"
  jpa:
    databasePlatform: "org.hibernate.dialect.H2Dialect"
  data:
    mongodb:
      uri: "mongodb+srv://fabio:4770@authdb.0mtus.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
